fantasy_football_tournament_admin_main:
    resource: "routing/main.yml"
    prefix:   /main

fantasy_football_tournament_admin_coach:
    resource: "routing/coach.yml"
    prefix:   /coach

fantasy_football_tournament_admin_coach_team:
    resource: "routing/coach_team.yml"
    prefix:   /coachTeamfantasy_football_tournament_admin_ranking:
    resource: "routing/ranking.yml"
    prefix:   /ranking