_ws_index:
  path:     /index
  defaults: { _controller: FantasyFootballTournamentCoreBundle:Default:index }
_ws_version:
  path:     /version
  defaults: { _controller: FantasyFootballTournamentCoreBundle:Default:getVersion }
_ws_get_editions:
  path: /Editions
  defaults: { _controller: FantasyFootballTournamentCoreBundle:Default:getEditionList }
_ws_get_edition_list:
  path: /EditionList
  defaults: { _controller: FantasyFootballTournamentCoreBundle:Default:getEditionList }
_ws_get_current_edition:
  path: /Edition/current
  defaults: { _controller: FantasyFootballTournamentCoreBundle:Default:getCurrentEdition }