<?php

namespace FantasyFootball\TournamentCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    
    public function countScheduledGamesByEditionAndRound($editionId,$round){
        $count = $this->getQueryBuilderCountForScheduledGamesByEditionAndRound($editionId,$round)
            ->getQuery()
            ->getSingleScalarResult();
        return $count;
    }
                
                
    public function getQueryBuilderCountForScheduledGamesByEditionAndRound($editionId,$round)
    {
        $qb = $this->createQueryBuilder('g');
        $qb->select('COUNT(g)')
            ->where($qb->expr()->andX(
                $qb->expr()->eq('g.edition', $editionId),
                $qb->expr()->eq('g.round',$round),
                $qb->expr()->eq('g.status','\''.Game::SCHEDULED.'\'')));
        return $qb;
    }
}
