<?php

namespace FantasyFootball\TournamentCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRepository extends EntityRepository
{
    public function getQueryBuilderForRaceByEditionOrLesser($editionId)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->where($qb->expr()->lt('r.edition', $editionId));
        $qb->orderBy('r.frenchName');
        return $qb;
    }
    
    public function getRaceByName($name)
    {
      $qb = $this->createQueryBuilder('r');
      $race = null;
      if('' == $name){
        $race = $qb->where($qb->expr()->eq('r.id',1))->getQuery()->getSingleResult();
      }else{
        $race = $qb->where($qb->expr()->eq('r.frenchName',"'".$name."'"))->orWhere($qb->expr()->eq('r.englishName',"'".$name."'"))->getQuery()->getSingleResult();
      }
      return $race; 
    }
}
