<?php

namespace FantasyFootball\TournamentCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRepository extends EntityRepository
{
    public function getQueryBuilderForRaceByEditionOrLesser($editionId)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->where($qb->expr()->lt('r.edition', $editionId));
        $qb->orderBy('r.frenchName');
        return $qb;
    }
}
