
_add_coach_team:
   path:    /add/{edition}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:CoachTeam:Add }
   requirements:
      edition:  \d+

_modify_coach_team:
   path:    /modify/{coachTeamId}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:CoachTeam:Modify }
   requirements:
      coachTeamId:  \d+

_delete_coach_team:
   path:    /delete/{coachTeamId}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:CoachTeam:Delete }
   requirements:
      coachTeamId:  \d+

_load_coach_team:
   path:    /load/{edition}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:CoachTeam:Load }
   requirements:
      edition:  \d+

_view_coach_team:
   path:    /view/{coachTeamId}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:CoachTeam:View }
   requirements:
      coachTeamId:  \d+

_list_coach_team:
   path:    /list/{edition}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:CoachTeam:List }
   requirements:
      edition:  \d+