fantasy_football_tournament_admin_main:
   path:    /{edition}/{round}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:Main:index,edition :13,round :-1 }
   requirements:
      edition:  \d+
      round:  \d+
fantasy_football_tournament_admin_next:
   path:    /next_round/{edition}
   defaults: { _controller: FantasyFootballTournamentAdminBundle:Main:nextRound,edition :13 }
   requirements:
      edition:  \d+